### ISSUE TITLE
Custom Domain Name

### ISSUE THREAD

**Issue by Kullsno2** [lynn/lynn.github.io#3]
I have a doubt regarding custom names for github pages. I see a cname file in your repository. But I want to know how you configured your DNS record to point it to your blog. Can you please elaborate?

**Comment by lynn** [comment]
GitHub Pages [has some good information on this](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). It's been a while, but I think I just followed the steps in "setting up an apex domain". I hope that helps!

**Comment by Kullsno2** [comment]
Thanks for the reply. I have read the information on the links you provided. But you asked me to go to the apex domain part which relies on creating an aname record. But I have noted that you have a cname file which is useful for "setting up a www subdomain". That's all I wanted to say and thanks Github!
